### ISSUE TITLE
Documentation improvement: Parts

### ISSUE THREAD

**Issue by Cybolic** [SukkoPera/OpenAmigaJoyMouseSwitcher#3]
I may just be new to the process, but I haven't been able to find a list of the parts that need to be soldered on to this board. I've tried googling for some of the numbers listed on the schematic, but with little success.
Could the documentation be updated to include a list of the parts needed, apart from just the pcb?

**Comment by SukkoPera** [comment]
What you're looking for is called BOM (Bill Of Materials), and you can find it under Releases in the top bar.

**Comment by Cybolic** [comment]
Thanks for the help! Do you happen to have a more detailed version of this?
I'm new to building things like this and a little more information would be very helpful. For example, C5 needs a 10μF capacitor but what voltage rating (since the port provides 5V I assume anything over 10V but I'd really like to be sure)? U3 needs an NE555 but does it make a difference whether it's an NE555N or NE555P (I hear the voltage ratings are different on these)?

Are these things already in the files somewhere or is it up to each builder to figure out?

**Comment by SukkoPera** [comment]
These things are usually up to the builder. As a general rule, detailed instructions are given only when a somewhat specific part is needed, otherwise indications remain pretty generic, as actually:
- C5 is not needed, all boards I've build are fine without it. If you really wanna use it, any voltage will be fine, since I think the lowest you will find are 16V, and there's nothing higher than 5V on the board, as you say.
- Literally any NE555 will be fine. I don't even know which ones I use, lol :).

So all you need is just common sense and maybe a bit of googling, but there's not really much that can go wrong.

**Comment by Cybolic** [comment]
Alright, that calms me down a bit; thanks again for the help :)
I'm completely new to picking my own parts and building anything that doesn't just require adding wires to something. I've already burned out one of my CIA chips - by plugging in a joystick while the system was on, the very reason I'm looking to build your switcher - so I'm a bit paranoid that I might mess something up.

**Comment by SukkoPera** [comment]
Don't worry, you just need to make up some experience :).
